# Generated by Django 4.2.6 on 2023-10-08 10:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='idNumber',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
