# Generated by Django 4.2.6 on 2023-10-08 12:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_useraccount_idnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='photo',
            field=models.FilePathField(blank=True, null=True, path=app.models.images_path),
        ),
    ]
