# Generated by Django 4.2.6 on 2023-10-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_useraccount_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.FilePathField(blank=True, null=True, path='static/images/events'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='photo',
            field=models.FilePathField(blank=True, null=True, path='static/images/users'),
        ),
    ]
