# Generated by Django 4.2.6 on 2023-10-08 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_useraccount_country_useraccount_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='activities',
        ),
        migrations.AddField(
            model_name='activity',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default=1, max_length=63),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city'),
        ),
    ]
