# Generated by Django 4.2.6 on 2023-10-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_event_activities_activity_event_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.FilePathField(blank=True, null=True, path='dist/assets/images/events/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='photo',
            field=models.FilePathField(blank=True, null=True, path='dist/assets/images/users/'),
        ),
    ]
