# Generated by Django 4.2.6 on 2023-10-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.FilePathField(blank=True, null=True, path='assets/images/events/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='photo',
            field=models.FilePathField(blank=True, null=True, path='assets/images/users/'),
        ),
    ]
