# Generated by Django 4.2.6 on 2023-10-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_event_photo_alter_useraccount_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
