# Generated by Django 4.2.6 on 2023-10-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_captcha_useraccount_login_tries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captcha',
            old_name='name',
            new_name='answer',
        ),
    ]
